### ISSUE TITLE
React components

### ISSUE THREAD

**Issue by geclos** [latitude-dev/latitude#105]
# WAT
We want to offer a standalone library of react components that communicate with a Latitude backend, so that you can easily integrate more deeply Latitude into existing codebases.

## TODO
- [x] Implement data layer in `@latitude-data/react` [here](https://github.com/latitude-dev/latitude/pull/225/files)
- [x] Implement `latitude-embed` JS component to communicate with an embedded iframe of a latitude app [here](https://github.com/latitude-dev/latitude/pull/286)

**Comment by Thawab8** [comment]
can this enable us to build our own component? for example using this as date range https://ui.shadcn.com/docs/components/date-picker

**Comment by geclos** [comment]
Yup, as part of the react library there will be a state manager to handle communication with a latitude backend, so that you can integrate create your own components that communicate with Latitude.

What I'm thinking about (pseudo-code, don't take it too seriously):

```typescript
import { useQuery } from '@latitude-data/react'

function MyCustomReactComponent () {
  const { data: queryResult, isLoading } = useQuery('titles') // this takes care of communicating with a Latitude backend and holding the frontend state

  console.log(queryResult) // or do whatever you want with it

  // ...
}
```

**Comment by andresgutgon** [comment]
@Thawab8 documentation for getting data from your Latitude project in your react project can be found here 
https://docs.latitude.so/guides/embed/react-components

Please let us know if something is not clear
