### ISSUE TITLE
VS Code extension

### ISSUE THREAD

**Issue by geclos** [latitude-dev/latitude#108]
Latitude does some automatic transformations to your code that do no play nicely with existing lsps and code completion, we need to provide at least a VS Code extension so that developing a Latitude app feels natural from the code editor.

**Comment by csansoon** [comment]
We have published a basic [vscode extension](https://marketplace.visualstudio.com/items?itemName=LatitudeData.latitude-vscode) to add code syntax and run queries and the dev server from within vscode itself.
