### ISSUE TITLE
`latitude run` improvements

### ISSUE THREAD

**Issue by cesr** [latitude-dev/latitude#113]
- [ ] Table cuts off the last 2 results and there's no way to navigate to them
---
- [ ] Accept full file paths in the `run` command.

Right now the `latitude run` command accepts referring to queries just with the name of the file.

We want to support VSCode tasks to make the experience more streamlined, so the command needs to accept full file paths too through a flag or parameter.

**Comment by csansoon** [comment]
"Accept full file paths in the run command" moved to a [different issue](https://github.com/orgs/latitude-dev/projects/1/views/4?pane=issue&itemId=59281406)
