### ISSUE TITLE
Encrypted params

### ISSUE THREAD

**Issue by andresgutgon** [latitude-dev/latitude#151]
# What?
We want to allow users of the framework to pass encrypted params that they can use when embedding the view in an iframe. Example:

``` javascript
<iframe src="https://your-latitudepage.com/some/query?secret=ENCRYPTED" />
```

So the idea is to pass to the API this `secret` or whatever you want to call your secret param and decrypt it on the server so only the owner of `your-latitudepage.com` can know what's the value of `ENCRYPTED`.

## Considerations
We need to think about how to differentiate between encrypted and non-encrypted params. One idea could be to add a prefix to the value or the name of the param
To the name:
``` bash
lt__secret=ENCRYPTED
```
To the value:
``` bash
secret=lt--ENCRYPTED
```
I think both ways can work

We also need to document how encryption work. Users needs to have a `LATITUDE_SECRET_KEY` in their `.env` file (which should be in the `.gitignore` file of the data project). The idea is to do what Rails does. Use this `LATITUDE_SECRET_KEY` do decrypt it on latitude's server.

On their side they need to encrypt the value of the encrypted params in the same way and with the same `LATITUDE_SECRET_KEY`. TO_BE_DEFINED

I think nothing need to be done in terms of using the encrypted param in queries or views. In a view users do `param('secret')` or whatever name they use for this param. And this send to the API the param encrypted. Is the server which before passing to the query builder decrypt the params with `LATITUDE_SECRET_KEY`

It should fail if we find some param that needs to be decrypted and we don't have the secret key. Also it should not fail if decryption fail. If someone pass an incorrect encrypted key we pass through the param to the query and the query will fail

**Comment by csansoon** [comment]
We can easily differentiate between encrypted and non-encrypted params thanks to our `custom_types` module. Encrypted params could be formatted as `key=$encrypted:<value>` or something like that.

**Comment by andresgutgon** [comment]
I like using an already stablished convention +1
