### ISSUE TITLE
Notify new CLI versions

### ISSUE THREAD

**Issue by samulatitude** [latitude-dev/latitude#153]
Currently the Latitude CLI update is a manual `npm update -g @latitude-data/cli`, it doesn't notify when there is a new version and may cause bugs or incompatibilities. We should notify users of new CLI versions when they use a command.

**Comment by andresgutgon** [comment]
This is what Storybook does. Would be something like this?
<img width="897" alt="image" src="https://github.com/latitude-dev/latitude/assets/49499/ece07c9b-b7aa-4bfb-937d-d3e9fa32cdd6">

**Comment by geclos** [comment]
Makes sense! We should also handle different messages for each type of version, if it's minor or patch it's ok to strongly suggest to do a latitude update. If it's a major version we should suggest they visit firs the changelog.
