### ISSUE TITLE
Migrate mysql connector to mysql2

### ISSUE THREAD

**Issue by geclos** [latitude-dev/latitude#173]
We currently use node's mysql package which is old and does not support some critical features from new mysql versions. We need to migrate to [mysql2](https://www.npmjs.com/package/mysql2) asap.

**Comment by cdaraujo1** [comment]
@geclos if this could be useful somehow, I have changed two items:

the `package-lock.json` in my latitude project directory from mysql to mysql2

```json
[...]
"node_modules/@latitude-data/mysql-connector": {
      [...]
      "dependencies": {
        "@latitude-data/base-connector": "^1.1.0",
        "@latitude-data/query_result": "^0.2.0",
        "mysql2": "^3.9.2"
      }
    }
      [...]
```

and the `my-latitude/node_modules/@latitude-data/mysql-connector/dist/index.js`

```
import { createPool } from 'mysql2';
```

and it worked perfectly.

**Comment by geclos** [comment]
Yup that's essentially what we need to do [here](https://github.com/latitude-dev/latitude/blob/7f537cd5887a31d3bb6168a5773bacaf3276a4e3/packages/connectors/mysql/src/index.ts#L9), we just haven't had the bandwith yet. I'll try to squeeze it next week.
