### ISSUE TITLE
Revert support to npm

### ISSUE THREAD

**Issue by geclos** [latitude-dev/latitude#185]
From the get go we tried to support whatever package manager the user was using in Latitude's CLI: pnpm yarn or npm. The problem with this is that we either have to ask the user what manager they want the CLI to use or we have to take a guess, which more often than not could be wrong. In order to deliver a more robust solution and taking into consideration our bandwith we are gonna remove support for alternative package managers and instead focus on providing a rock solid solution with npm, which ships with all versions of NodeJS and is plenty fast for all versions of node that Latitude supports.

**Comment by andresgutgon** [comment]
Done here https://github.com/latitude-dev/latitude/pull/187
