### ISSUE TITLE
Make Pie chart columns configurable

### ISSUE THREAD

**Issue by andresgutgon** [latitude-dev/latitude#201]
# What?
Now the columns used from the query in a `<PieChart />` are always the first as `dimension` and the second as `metric`

So for example a table like this
| Source        | Amounts | Whatever |
|---------------|---------|----------|
| Search Engine | 1048    | 33       |
| Direct        | 735     | 33       |
| Email         | 580     | 33       |
| Union Ads     | 484     | 33       |
| Video Ads     | 300     | 33       |

You can pass `metric` and `dimension` like this

``` javascript
<PieChart metric='Amounts' dimension='Source' />
```

## The problem
If for some reason you want to use a data that looks like this 
| Source        | Whatever | Amounts |
|---------------|----------|---------|
| Search Engine | 33       | 1048    |
| Direct        | 33       | 735     |
| Email         | 33       | 580     |
| Union Ads     | 33       | 484     |
| Video Ads     | 33       | 300     |

It wont work. We have to implement `metric` and `dimension` props for pie chart

**Comment by geclos** [comment]
Is this still true @andresgutgon?

**Comment by andresgutgon** [comment]
Yes
