### ISSUE TITLE
Table component improvements

### ISSUE THREAD

**Issue by geclos** [latitude-dev/latitude#215]
- Implement **frontend-based sorting** in the Table component so that users can easily sort tables ascendingly/descendingly by simply clicking on a column header. The behavior should cycle between three states: I click once on the header; it sorts ascendingly, I click again; it sorts descendingly, I click again; it removes the sorting altogether. The sorting is purely frontend-based – it should not trigger any query recomputation nor imply any action on the backend side of things. I should be able to disable sorting by passing a sorting boolean prop to the Table component. By default, sorting is enabled in the component.

- Implement sticky header in the Table component, so that when I scroll on big tables I keep seeing the column headers. Users should be allowed to disable the sticky header behavior via a boolean prop. Sticky header behavior should be enabled by default.

**Comment by lakshaygoyal01** [comment]
Hi @geclos,  I have successfully set up the project locally and have fixed the Sticky header issue, working on the sorting part.

Can you please assign this issue to me?

Thanks

**Comment by geclos** [comment]
Done 👌🏼 thanks!

**Comment by lakshaygoyal01** [comment]
Thanks, Soon will open a PR to close the issue.🤟🏻

**Comment by lakshaygoyal01** [comment]
Hi @geclos, How do you want it to be sorted like sort according to some particular metric(title, release_year, etc.) Or should there be a select button in the UI to sort according to different metrics?

**Comment by geclos** [comment]
Hey @lakshaygoyal01, sorry the issue lacks a proper description, will update it asap.

To clarify, this issue is about adding frontend sorting to the table component, so that users can sort by clicking on the header of a particular column. So, for example, the table would sort itself alphabetically when I click the "description" column header. The sorting is purely frontend-based – it should not trigger any query recomputation nor imply any action in the backend side of things.

![image](https://github.com/latitude-dev/latitude/assets/1948929/1ecf7b33-7be1-4310-9865-f00866a8fb75)

Let me know if I there are any doubts.

**Comment by lakshaygoyal01** [comment]
Thank you @geclos for providing detailed clarification, will work on this and let you know if I encounter any challenges.
