### ISSUE TITLE
When creating a new query file, I have to restart the server for it to sync

### ISSUE THREAD

**Issue by cesr** [latitude-dev/latitude#248]
Steps to reproduce:
- Run `latitude dev` on a working project
- Add a query file to `/queries`
- Use that query file in a view
- Error shows up saying query not found
- Restart the server
- Now it works

Two more issues that might be related:
- If I update a query file, hot reloading doesn't work
- If I update a CSV file, I have to restart the server

**Comment by geclos** [comment]
taking a look ASAP

**Comment by geclos** [comment]
@cesr can't reproduce the issues you mentioned which points to some watchers malfunctioning at some point in your machine. Can you reproduce these issues consistently? The only one that I can reproduce consistently is:

> If I update a query file, hot reloading doesn't work

Which is to be expected actually not a bug, we just have not implemented hot reloading for queries

**Comment by andresgutgon** [comment]
> Which is to be expected actually not a bug, we just have not implemented hot reloading for queries

I think I saw that svelte/vite dev server is bi-directional even with spawn. So I think is possible to send a signal to the server when the query change to re-load

**Comment by cesr** [comment]
Okay got it, so I guess this issue should be turned into two separate ones:

- Hot reloading for queries
- CSV sync

Leaving this one to track only problems when syncing queries.
