### ISSUE TITLE
Issue when installing with python 3.12

### ISSUE THREAD

**Issue by carlosseru** [latitude-dev/latitude#302]
## Steps To Reproduce

Run npm install -g @latitude-data/cli
Installation is fine.
But when running latitude start it returns error due to python package distutils

### Environment

- Node version (`node -v`): 20.12.2
- npm version (`npm -v`): 10.5.0
- OS: macOS Monterey 12.6.7
- python: 3.12

## Expected Behavior

Installation success

## Actual Behaviour

Failed at import gyp. 
npm ERR! ModuleNotFoundError: No module named 'distutils'

## Workarounds

The library distutils has been removed in python 3.12
I fixed it by running pip3 install setuptools (https://stackoverflow.com/questions/69919970/no-module-named-distutils-but-distutils-installed)

**Comment by andresgutgon** [comment]
Maybe is related with issue
https://github.com/duckdb/duckdb/issues/9301

By default the connector we release use `duckdb` 

@carlosseru did you started the project with Netflix example or with the blank example?

If you did with Netflix can you try to start an empty project and connect other thing like `postgres` or `mysql`?

Anyway we need to confirm this and fix it. 
Thanks for reporting!

**Comment by geclos** [comment]
Adding the workaround to docs until we have a longterm fix
