### ISSUE TITLE
Data from CSV is not loaded

### ISSUE THREAD

**Issue by abgonzalez93** [latitude-dev/latitude#309]
## Steps To Reproduce

**latitude start**
Setting Latitude configuration.
Installing dependencies.
Downloading Netflix template.

**latitude dev**
Getting 404.

### Environment

- Node version (`node -v`): 18.20.2
- npm version (`npm -v`): 10.5.2
- OS: 22.04.3
- Browser: Firefox 125.0.1

## Actual Behaviour

Data from the CSV is not loaded.
**Query file not found at titles/***

![error](https://github.com/latitude-dev/latitude/assets/39385878/49c27ba3-871c-49ce-9e3a-51f0152f8550)

_**source.yml** by default has duckdb. ¿Is that correct if I want data from a static file (.csv)?_

![files](https://github.com/latitude-dev/latitude/assets/39385878/edb1b39d-1fff-4c64-ae69-cbf7b5431d6e)

**Comment by csansoon** [comment]
This issue is due to the project being outdated. Run `latitude update` from the project directory to update it and it should work.

The problem here is that we didn't updated the Netflix sample properly. Looking at it asap!

**Comment by geclos** [comment]
Yup this issue is fixed, closing it. @abgonzalez93 feel free to reopen if it persists.
