### ISSUE TITLE
Concat params in SQL

### ISSUE THREAD

**Issue by abgonzalez93** [latitude-dev/latitude#323]
### Environment

- Node version (`node -v`): 18.20.2
- npm version (`npm -v`): 10.5.2
- Latitude CLI version (`latitude --version`): 0.8.2
- Latitude project version (check `latitude.json` at the root of your project): 0.11.0
- OS: Ubuntu 22.04.3
- Database: MySQL

## Actual Behaviour
Is there anyway to concat a String with a param variable inside a **SQL code**?
For example, in my case, Im using a **LIKE** operator, which uses a % inside a string, **ie '%something%'**
So my question is, how can you concat a string with a param(variable) or even {interpolate(param(variable))}

_This is my code right now (but its not working tho)_
![imagen](https://github.com/latitude-dev/latitude/assets/39385878/c934b2b7-b435-46e2-9807-0e6bcfbda8b8)

**Comment by csansoon** [comment]
You can interpolate strings before adding it to the query, like this:
```sql
desc_agencia LIKE {'%' + param('agency_filter') + '%'}
```
or interpolate it if you need it:
```sql
desc_agencia LIKE {interpolate('%' + param('agency_filter') + '%')}
```

Also, you can use variables for improving the query readability:
```sql
{#if param('agency_filter', false)
  {filter = '%' + param('agency_filter') + '%'}
  AND desc_agencia LIKE {interpolate(filter)}
{/if}
```

**Comment by abgonzalez93** [comment]
Yeah, that actually helped. Thanks for your time!
It might be interesting if it's put into the website
