### ISSUE TITLE
Options to scale Latitude Cloud deployments

### ISSUE THREAD

**Issue by geclos** [latitude-dev/latitude#346]
## Feature Description

As a user I would like to be able to configure autoscaling policies of my Latitude Cloud deployments with a min and max number of instances depending on different load types

## Goal of Feature

Make Latitude Cloud deployments more resilient

## Current Solution / Workarounds

Talk to the Latitude Team and we'll manually scale your deployments if needed

**Comment by andresgutgon** [comment]
I think we're not going to work on this soon. I'll close it. Feel free to re-open
