### ISSUE TITLE
Changing the value of an input from React does not update the parameter in an embed

### ISSUE THREAD

**Issue by csansoon** [latitude-dev/latitude#360]
## Steps To Reproduce

1. Run `examples/sample-react`
2. Modify the value of `end_year` from the input in React, outside of the embed

### Environment

- Happens since `@latitude-data/react` version `0.6.2`

## Expected Behavior

It should update the value of the param inside the embed.

## Actual Behaviour

Does not update the value inside the embed. Every other type of events do work as expected.

## Hints

I suspect the problem might come from here: https://github.com/latitude-dev/latitude/pull/284

**Comment by geclos** [comment]
@andresgutgon this was resolved then no

**Comment by andresgutgon** [comment]
I couldn't reproduce with the latest versions of react embed and react-example.
