### ISSUE TITLE
Visualizations - Make dimensions more flexible instead of fixed px

### ISSUE THREAD

**Issue by samulatitude** [latitude-dev/latitude#378]
## Feature Description

Allow setting flexible dimensions instead of fixed dimensions in visualization components.

## Goal of Feature

Gain more control over chart dimensions to adapt them to different layouts or screen sizes as needed, instead of a fixed width and height that can cause unwanted scrolling or a broken design.

## Current Solution / Workarounds

Set a fixed height={} that works more or less in any screen size.

## Alternatives

@andresgutgon suggested that we could control the dimensions of visualizations from the container, so that the visualization would take the 100% available width and height defined by the parent.

**Comment by geclos** [comment]
But what is the specific proposal? 

> Allow setting flexible dimensions instead of fixed dimensions in visualization components.

How? What's the API?

**Comment by andresgutgon** [comment]
I am not sure. One idea we had is to have a `aspectRatio` prop so the height/width change in synchrony. 

Another idea is not use `height` prop and let parent wrapper defined width/height. I think for that we need to stop passing `height` or pass it `undefined`.
