### ISSUE TITLE
runQuery reactToParams is opt-in instead of opt-out like all the rest

### ISSUE THREAD

**Issue by geclos** [latitude-dev/latitude#450]
## Steps To Reproduce

Use runQuery in any context

## Expected Behavior

Should be opt-out like in charts, autocomputing should always be opt-in as it's an expensive operation

## Actual Behaviour

It autocomputes

## Workarounds

`runQuery('query', { reactToParams: false})` explicitly setting reactToParams to false stops the autocomputing

**Comment by Clemo97** [comment]
Why is everybody terrified of this issue 😂, anyway I just started exploring and using latitude. Great product you've built here.
As I haven't used 'runQuery' yet, I'll keep exploring and try it out today and try to reproduce the issue.
