### ISSUE TITLE
Support multiselect in Select component

### ISSUE THREAD

**Issue by geclos** [latitude-dev/latitude#451]
## Feature Description

Add multi-select support to Select. The multiselection would result in a list of items when the value gets interpolated to the query.

## Goal of Feature

Better UX, less repeated select components required.

## Current Solution / Workarounds

Use multiple Select components

## Alternatives

None

**Comment by csansoon** [comment]
This one requires creating a way to format and parse arrays in our `@latitude-data/custom-type` package
