### ISSUE TITLE
latitude cli displays framework version as well as cli version

### ISSUE THREAD

**Issue by bensullivan** [latitude-dev/latitude#452]
## Feature Description

Would be great if `latitude -v` could display both framework version as well as cli version.

## Goal of Feature

Determining the version of latitude framework in use

## Current Solution / Workarounds

Perform `latitude update` to see what version is in use.

**Comment by andresgutgon** [comment]
That PR should fix this issue. Now we show the `latitude.json` version of the app and the CLI version
![image](https://github.com/latitude-dev/latitude/assets/49499/8407f98a-16f9-412c-9452-83efa5533111)

This is the final change:
https://github.com/latitude-dev/latitude/pull/479
