### ISSUE TITLE
Download as CSV Not Disabling After Download

### ISSUE THREAD

**Issue by lakshaygoyal01** [latitude-dev/latitude#456]
## Steps To Reproduce

1. Click on the three-dot icon on the right of the charts.
2. Click on Download as CSV.

## Expected Behavior

After clicking the download option, the button should be disabled in the UI.

## Actual Behaviour
The button remains enabled in the UI after clicking the download option.

**Comment by lakshaygoyal01** [comment]
I would like to work on this by myself.

**Comment by andresgutgon** [comment]
Hi @lakshaygoyal01 thanks for the report. Yes, work on it. But remember to enable it again when the download request finishes.

**Comment by Clemo97** [comment]
@lakshaygoyal01 and @andresgutgon  Does this really qualify as an issue? I've been using the download feature and I don't really feel it even qualifies as a bug
[Uploading Screencast from 19-06-24 09:36:48.webm…]()
