### ISSUE TITLE
Cannot read properties of undefined (reading 'host')

### ISSUE THREAD

**Issue by abgonzalez93** [latitude-dev/latitude#487]
### Environment

- Node version (`node -v`): 18.20.2
- npm version (`npm -v`): 10.8.1
- Latitude CLI version (`latitude --version`): 1.10.1
- Latitude project version (check `latitude.json` at the root of your project): 2.0.1
- OS: Ubuntu 22.04.3
- Browser: Firefox 126.0.1
- Database: MySQL

## Actual Behaviour

This has been happening since v2.0.0
I had to downgrade Latitude to v1.2.3 to make it works

![latitude-error](https://github.com/latitude-dev/latitude/assets/39385878/f85540f5-dd31-46e3-bcc1-4514704d3fe3)

**Comment by andresgutgon** [comment]
Hi @abgonzalez93 can you update to the latest mysql connector version?

```
npm i @latitude-data/mysql-connector@latest
```

**Comment by abgonzalez93** [comment]
It is working now!

It's weird though. Always I start working, the first thing I do is updating versions in my Latitude server.
I always do the following 3 steps:

1. `npm update -g @latitude-data/cli`
2. `npm update`
3. `latitude update`

`npm update` is supposed to update libraries from package.json

![imagen](https://github.com/latitude-dev/latitude/assets/39385878/71648c02-78f9-4ea3-9303-4df794d63d78)

But MySQL connector was previously on `v2.1.2`
Somehow ii's like I had to "force" the update to the latest version

**Comment by andresgutgon** [comment]
I guess is because you had in package.json `^2.1.2` no? That don't bump the mayor version. I think is `*2.1.2` so `npm update` can bump to `*3.0.0`. 

Anyway we're preparing `latitude update` to do that if you update to latest app version also update `CLI` and your connectors.

**Comment by abgonzalez93** [comment]
Great!
