### ISSUE TITLE
Capture node warnings with telemetry

### ISSUE THREAD

**Issue by andresgutgon** [latitude-dev/latitude#508]
What?
We removed node warnings in production because in general are not helpful for users
We did it here
https://github.com/latitude-dev/latitude/pull/506/files#diff-6617ab2b81b66671c8ee19cdac270915af8f2aeafb2c43b6b31decd8bc61492fR9

But we want somehow capture this information 

Maybe in telemetry

**Comment by csansoon** [comment]
After removing all warning listeners, it no longer prints it to the user terminal, but we don't capture it either.
We can easily fix it by subscribing to the warning event right after removing all other listeners.
```ts
process.removeAllListeners('warning')
process.on('warning', info => {
  // Capture warning with telemetry
}) 
```
