### ISSUE TITLE
Dynamic Query creation from front-end

### ISSUE THREAD

**Issue by navyademo1** [latitude-dev/latitude#539]
Hi ,
Can anyone help me here

Scenario :
I have latitude server running and integrated the latiude api in react app and getting the expected result. But , my question here is instead of creating a query in latitude server manually then invoking it from the react app is that possible to create the query via frontend then store it in latitude queries folder ?

**Comment by andresgutgon** [comment]
Hi, @navyademo1. I'm afraid that's not possible with plain Latitude. You can always do an API endpoint in your server to write the queries on disk.

**Comment by navyademo1** [comment]
Thanks for the update

**Comment by andresgutgon** [comment]
No problem, I'll close the issue but feel free to re open if you have more questions
