### ISSUE TITLE
Can we configure Cassandra as data source?

### ISSUE THREAD

**Issue by navyademo1** [latitude-dev/latitude#543]
Hi,

I have a query, can we connect to Cassandra data source, if not 

1. Can we expect in near future?
2. Is there a way to implement custom connector for this?

**Comment by andresgutgon** [comment]
> Is there a way to implement custom connector for this?

Yes, never worked with Casandra. But maybe using under the hood something like this package https://github.com/datastax/nodejs-driver and implementing the methods in [BaseConnector](https://github.com/latitude-dev/latitude/blob/main/packages/source_manager/src/baseConnector/index.ts#L33)

Any connector in connectors folder can serve as example:
https://github.com/latitude-dev/latitude/tree/main/packages/connectors


We might implement ourselves I'll keep the issue open.

**Comment by navyademo1** [comment]
Got it, thanks for the update.

**Comment by navyademo1** [comment]
Hi @andresgutgon , I just need to add this basic logic in BaseConnector?

const cassandra = require('cassandra-driver');

const client = new cassandra.Client({
  contactPoints: ['h1', 'h2'],
  localDataCenter: 'datacenter1',
  keyspace: 'ks1'
});

const query = 'SELECT name, email FROM users WHERE key = ?';

client.execute(query, [ 'someone' ])
  .then(result => console.log('User with email %s', result.rows[0].email));
  
  am new to the JavaScript basically from Java background.

**Comment by navyademo1** [comment]
Can you please share which will be the landing file of the latitude project when we trigger the endpoint from react app..?
